
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/RahulKandagatla/golang-restful-api-tutorial
    steps:
      - checkout
      - setup_remote_docker

      - run: go get -v -t -d ./...
      
      - run:
          name: Build image
          command: |
            docker build -t golang-restful-api-tutorial:$CIRCLE_SHA1 .